---
title: "USA House Election Results"
author: "Olivér Lubics"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

This is my final project for the Statistical Programming PhD course at ELTE. I am going to explore the dataset on the US House of Representatives election results.

```{r setup, results='hide', message=FALSE}
# Loading the necessary packages and disabling scientific notation
library(tidyverse)
library(tidytuesdayR)

options(scipen = 999) 
```

# Getting the data

```{r}
tuesdata <- tt_load('2023-11-07')
house_data <- tuesdata$house

```

# Exploratory data analysis

```{r}
# Checking the structure of the data
str(house_data)

# Checking the first rows of the data
head(house_data)

# Checking the last rows of the data
tail(house_data)

# So far, I can see that this dataset has the US House election results from 1976 to 2022 for each state. 

# Checking the number of missing values in each column
colSums(is.na(house_data))
# There are no missing values in the dataset.

# Checking the number of political parties in the elections. Sorting the parties by the number of elections they participated in.
house_data %>% 
  count(party, sort = TRUE)
# It's really interesting to see that there are 478 parties that participated in the elections, while there are only 2 major parties in the US (Democratic and Republican). For simplicity, I will only focus on these two parties. 

# Removing the parties that are not Democratic or Republican
house_data_cleaned <- house_data %>% 
  filter(party == "DEMOCRAT" | party == "REPUBLICAN")

# Adding a new column that shows the percentage of votes for each candidate and removing the all uppercase format from the party names
house_data_cleaned <- house_data_cleaned %>% 
  mutate(percent_of_votes = (candidatevotes / totalvotes) * 100) %>%
   mutate(party = str_to_title(tolower(party)))

# Plotting the percentage of votes by year and party
house_data_cleaned %>% 
  ggplot(aes(x = year, y = percent_of_votes, color = party)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
    scale_color_manual(values = c("Democrat" = "blue", "Republican" = "red")) +
  labs(title = "Percentage of votes by year and party",
       x = "Year",
       y = "Percentage of votes",
       color = "Party",
       caption = "Each point represents the result of a candidate in the given year.") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    plot.caption = element_text(hjust = 0.5))
# It's interesting to see that the percentage of votes for the Democratic party has been decreasing since 1976, while the percentage of votes for the Republican party has been increasing since then. In any case, the results of the two parties' candidates are generally quite close.

# Plotting the number of votes by year and party on a line plot
house_data_cleaned %>% 
  group_by(year, party) %>% 
  summarise(total_votes = sum(candidatevotes)) %>%
  ggplot(aes(x = year, y = total_votes, color = party)) +
  geom_line() +
  scale_color_manual(values = c("Democrat" = "blue", "Republican" = "red")) +
  labs(title = "Number of votes by year and party",
       x = "Year",
       y = "Number of votes",
       color = "Party") +
  scale_x_continuous(
    breaks = unique(people$year),
    labels = function(x) substring(x, nchar(x) - 1)
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    plot.caption = element_text(hjust = 0.5)
  )

# It's interesting to see how much voter turnout varies the years. I think that big variation could be caused by the fact that the US House elections are held every two years, and the turnout is could be higher, when the presidential election is also happening in the same year. I will look into this.

# Adding a new coloumn that shows if the particular year was a midterm or presidential election year in the US. I checked the years on Wikipedia.
house_data_cleaned <- house_data_cleaned %>% 
  mutate(election_type = ifelse(year %% 4 == 0, "Presidential", "Midterm"))

# Plotting the number of votes by year and election type on a line plot
house_data_cleaned %>% 
  group_by(year, election_type) %>% 
  summarise(total_votes = sum(candidatevotes)) %>%
  ggplot(aes(x = year, y = total_votes, color = election_type)) +
  geom_line() +
  geom_point() +
  labs(title = "Number of votes by year and election type",
       x = "Year",
       y = "Number of votes",
       color = "Election type") +
  scale_x_continuous(
    breaks = unique(people$year),
    labels = function(x) substring(x, nchar(x) - 1)
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    plot.caption = element_text(hjust = 0.5)
  )

```

